### ISSUE TITLE
跨云服务商下不通

### ISSUE THREAD

**Issue by zhangguanzhang** [opsnull/kubernetes-troubleshooting-book#1]
flannel的vxlan，只有pod所在的node才能访问svc-clusterip如何解决，8472已开

**Comment by zhangguanzhang** [comment]
我自己找到原因了，我就是不说-，-

**Comment by opsnull** [comment]
@zhangguanzhang 

> 我自己找到原因了，我就是不说-，-

 I am ashamed for you！
